"""LLM engine for the fusion layer — CURRENTLY SIMULATED.

Per the operator's instruction, the real LLM API call is commented out and
the narration is produced deterministically in-code (acting as the LLM
ourselves). This is viable precisely because the fusion graph already holds
the structured findings + timeline; the LLM's only job is narration, which
here is templating + retrieval.

To switch to a real model: uncomment ``_real_llm`` below, ensure the LLM
config/API key is set, and route ``generate_report`` / ``chat`` through it.
No graph/correlation code changes — only this boundary swaps.
"""

from __future__ import annotations

from . import render, severity as sev
from .correlate import _assets_of, _host_label

SIMULATED = True   # flip to False once a real model is wired


# ---------------------------------------------------------------------------
# Real-LLM boundary (commented — this is the ONLY place the API is touched)
# ---------------------------------------------------------------------------
# def _real_llm(system_prompt: str, user_message: str, *, run_id=None) -> str:
#     """Production path. The distilled graph is small (KB), so this is cheap.
#     from services.agentic.analyzers import call_llm
#     from services.memory.pipeline import _llm_config_from_runtime
#     return call_llm(user_message, system_prompt,
#                     _llm_config_from_runtime(), run_id=run_id)
# ---------------------------------------------------------------------------


REPORT_SYSTEM_PROMPT = (
    "You are a senior DFIR consultant. Narrate the provided correlated incident "
    "graph as a customer-facing case report with three sections: executive/risk "
    "overview, an infrastructural attack timeline (kill-chain phased, per host), "
    "and per-host detail. Cite hosts, processes, accounts, and IOCs verbatim. Do "
    "not invent anything not in the graph."
)
CHAT_SYSTEM_PROMPT = (
    "You are a DFIR assistant answering questions about ONE correlated incident "
    "graph. Answer only from the graph facts provided; cite the host + evidence "
    "source for each claim; never speculate beyond the data."
)


def generate_report(graph, *, window=None, min_severity="informational",
                    initial_access=None, case_name="Case", run_id=None) -> str:
    """The case report. (Simulated narrator = deterministic render.)"""
    # PRODUCTION: payload = render.distilled(graph, window=window, min_severity=min_severity)
    #             return _real_llm(REPORT_SYSTEM_PROMPT, json.dumps(payload), run_id=run_id)
    md = render.report(graph, window=window, min_severity=min_severity,
                       initial_access=initial_access, case_name=case_name)
    return md + "\n\n---\n_Report generated by the in-graph narrator " \
                "(simulated LLM — deterministic). Switch to a live model in llm_sim.py._\n"


def chat(graph, question: str, history=None, *, window=None, min_severity="informational",
         run_id=None) -> str:
    """Grounded Q&A over the graph (simulated = deterministic retrieval)."""
    # PRODUCTION: payload = render.distilled(graph, window=window, min_severity=min_severity)
    #   ctx = json.dumps(payload); turns = history or []
    #   return _real_llm(CHAT_SYSTEM_PROMPT, f"{ctx}\n\nQ: {question}", run_id=run_id)
    q = (question or "").lower()
    _, findings = render.scope(graph, window=window, min_severity=min_severity)

    def cite(f):
        srcs = "/".join(f.sources) or "?"
        return f"- **[{f.severity}]** {f.title} — {f.summary}  _(source: {srcs})_"

    # 1) host-focused
    for a in graph.by_type("asset"):
        if a.label and a.label.lower() in q:
            af = [f for f in findings if a.id in f.asset_ids]
            if af:
                return f"On **{a.label}**:\n" + "\n".join(cite(f) for f in af)

    # 2) lateral movement / how did they move / pivot
    if any(k in q for k in ("lateral", "move", "moved", "pivot", "spread", "how did")):
        xh = [f for f in findings if f.kind == "cross_host"]
        if xh:
            return "Cross-host / lateral movement evidence:\n" + "\n".join(cite(f) for f in xh)
        return "No deterministic cross-host (lateral-movement) link surfaced in the graph for this window."

    # 3) timeline / when / first
    if any(k in q for k in ("timeline", "when", "first", "initial", "order", "happen")):
        tl = render.timeline(graph, window=window)
        if tl:
            lines = [f"- `{r['ts'] or '—'}` · {r['host']} · [{r['phase']}] {r['title']}" for r in tl[:20]]
            return "Attack timeline (chronological):\n" + "\n".join(lines)

    # 4) indicator / IP / account lookup
    for e in graph.entities.values():
        if e.type in ("ioc", "account") and e.label and e.label.lower() in q:
            hosts = ", ".join(_host_label(graph, x) for x in _assets_of(e))
            tag = " (CROSS-HOST)" if "cross_host" in e.flags else ""
            return (f"**{e.label}** ({e.type}){tag} seen on: {hosts}. "
                    f"Severity {e.severity}, sources {'/'.join(e.sources)}.")

    # 5) default: top findings
    top = sorted(findings, key=lambda f: -sev.rank(f.severity))[:8]
    if not top:
        return "No findings above the current severity threshold in this window."
    return "Top findings for this case:\n" + "\n".join(cite(f) for f in top)
