"""Shared input-validation helpers for VQL + subprocess injection defense.

Used by route handlers that read operator-supplied values from the
request body and feed them into Velociraptor VQL strings or shell
commands. The goal is twofold:

  1. Shape validation — reject inputs whose CHARACTER SET can't appear
     in a legitimate request (e.g. quotes, backticks, semicolons in a
     Velociraptor client_id). This is the strongest guarantee because
     legitimate inputs never trigger it.

  2. Safe escaping for free-form text fields where shape validation
     would be too restrictive (e.g. operator-supplied run names with
     apostrophes in case nicknames like "O'Brien Q4 Sweep"). For those
     we double up `'` per VQL's single-quote escape and reject control
     characters.

History: 2026-06-09 Mythos security review surfaced confirmed RCE via
`client_id` (velociraptor_routes.py — shell=True), `target_users` /
`target_ips` (Azure DFIR-O365RC — PowerShell + shell=True), and CVE
hunt `name` (cve_routes.py — VQL execve). The three fixes routed
through here are #2 + #4; #3 (Azure) is deferred until the operator
can validate against a real tenant.
"""

import re

# Velociraptor's own ID conventions. Generated by the server, never
# operator-typed. The exact alphabet is "C." then 16 hex chars by
# default but we permit up to 32 for forward-compat with longer IDs.
_CLIENT_ID_RE = re.compile(r'^C\.[0-9a-f]{1,32}$')

# Flow IDs are uppercase alphanumerics after "F."
_FLOW_ID_RE = re.compile(r'^F\.[0-9A-Z]{1,32}$')

# Hunt IDs follow the same shape as flow IDs but with H prefix.
_HUNT_ID_RE = re.compile(r'^H\.[0-9A-Z]{1,32}$')

# Artifact / blueprint names follow Velociraptor's documented convention:
# dot-separated CamelCase segments, with `_` `-` `:` allowed.
# Examples: Generic.Client.Info, Windows.KapeFiles.Targets,
# _KapeTriage, Custom.Server.Import.TenRoot.Artifacts
_ARTIFACT_NAME_RE = re.compile(r'^[A-Za-z0-9_.\-:]{1,128}$')


def is_valid_client_id(value: str) -> bool:
    """True iff the string is a well-formed Velociraptor client ID.

    Used at request-handler entry points to reject inputs whose shape
    can't possibly have come from Velociraptor's own ID generator
    (e.g. shell metacharacters, quotes, spaces, path separators).
    """
    return bool(value) and bool(_CLIENT_ID_RE.match(value))


def is_valid_flow_id(value: str) -> bool:
    """True iff the string is a well-formed Velociraptor flow ID."""
    return bool(value) and bool(_FLOW_ID_RE.match(value))


def is_valid_hunt_id(value: str) -> bool:
    """True iff the string is a well-formed Velociraptor hunt ID."""
    return bool(value) and bool(_HUNT_ID_RE.match(value))


def is_valid_artifact_name(value: str) -> bool:
    """True iff the string looks like a Velociraptor artifact / blueprint
    name (dotted CamelCase with underscores, dashes, colons).

    Used to validate fields like `kape_target`, `artifact_name`, and
    other selectors that flow into VQL via string concatenation.
    """
    return bool(value) and bool(_ARTIFACT_NAME_RE.match(value))


def validate_client_ids_list(values, max_items: int = 5000):
    """For routes that accept a `client_ids` LIST (agentic, scheduler,
    analyze-existing, etc.): coerce to list, reject non-list payloads,
    enforce a length cap, and shape-validate every element via
    `is_valid_client_id`.

    Returns (cleaned_list, None) on success, or (None, error_message)
    on failure. Caller does:

        cleaned, err = validate_client_ids_list(data.get('client_ids'))
        if err:
            return jsonify({"error": err}), 400

    Empty input is allowed (returns `[]`) because some routes use
    `client_ids=[]` to mean "all targets" or have other code paths.
    The shape check still fires on every element when the list is
    non-empty.
    """
    if values is None:
        return [], None
    if not isinstance(values, list):
        return None, "client_ids must be a list of strings"
    if len(values) > max_items:
        return None, f"client_ids list too long (>{max_items} items)"
    cleaned = []
    for i, v in enumerate(values):
        if not v:
            continue
        if not isinstance(v, str):
            return None, f"client_ids[{i}] must be a string"
        if not is_valid_client_id(v):
            return None, f"client_ids[{i}] is not a valid Velociraptor client ID (must match C.<hex>)"
        cleaned.append(v)
    return cleaned, None


def escape_vql_string(value: str) -> str:
    """Make a free-form string safe to embed inside a VQL single-quoted
    literal via the standard SQL/VQL escape: double up every `'`.

    Use for fields like CVE hunt `name` / `description` where rejecting
    apostrophes would block legitimate IR data (case nicknames, vendor
    names). Also strips control characters that have no business in a
    hunt label and would interact badly with VQL multi-line parsing.

    The output is meant to be embedded between single quotes:

        f"hunt(description='{escape_vql_string(value)}', ...)"

    so the caller still owns the outer quoting; this helper handles
    only the in-string escape.
    """
    if value is None:
        return ''
    if not isinstance(value, str):
        value = str(value)
    # Drop ASCII control chars (incl. CR/LF/tab) — none of these are
    # legitimate in a hunt label or description.
    value = ''.join(ch for ch in value if ord(ch) >= 0x20)
    # VQL/SQL single-quote escape: double up every '.
    return value.replace("'", "''")
