"""Keep a module's compose file and the files it bind-mounts in sync.

THE BUG THIS EXISTS TO KILL
---------------------------
refresh_module_compose_file() ships the new release's docker-compose.yaml to a
box installed before it. That is correct and necessary — without it a structural
compose change (a mount, a healthcheck, a capability) stays FROZEN on that box
forever. But it copies the compose file and NOTHING ELSE, on purpose: the module
directory also holds real per-install state (secrets/, data/, generated certs)
that a directory mirror would clobber.

So when the ELK release added a `setup` service:

    volumes:
      - ./config/setup-kibana-user.sh:/usr/local/bin/setup-kibana-user.sh:ro
    entrypoint: ["/bin/bash", "/usr/local/bin/setup-kibana-user.sh"]

the compose file reached the appliance and the script did not. Docker does not
error on a bind mount whose host path is missing — it CREATES AN EMPTY DIRECTORY
there. `/bin/bash <a directory>` exits 126, and the operator gets "service
'setup' didn't complete successfully: exit 126" with nothing pointing at the
real cause. Half-delivery: the compose file and its dependencies out of sync.

IRIS mounts three shell scripts the same way. The next module to add a mounted
file inherits the same trap. So the fix is not "also copy that one script" —
it is to make the compose file itself the manifest.

THE INVARIANT
-------------
Every relative bind source in a module compose file is either:

  (a) shipped code — it exists in the release source tree, and the upgrade must
      deliver it; or
  (b) install-generated state — it does not exist in the release source tree,
      and something on the appliance must create it. Those are enumerated in
      INSTALL_GENERATED below, each with the step that creates it.

Anything else is a packaging mistake, and both halves are checkable:
tests/test_compose_mounts_are_delivered.py enforces it at CI time against the
repo, and verify_referenced_assets() enforces it at upgrade time against the
appliance, immediately before compose runs.

WHAT DELIVERY DOES, AND WHAT IT REFUSES TO DO
---------------------------------------------
deliver_referenced_assets() handles three cases:

  missing        -> copy it, preserving mode
  empty dir      -> Docker's leftover from a previous failed run; remove, copy
  file, differs  -> refresh it, keeping the old content at <name>.pre-upgrade

The refresh case was added the same day as the rest, because fill-the-gap alone
demonstrably was not enough. The ELK release that enabled xpack.security also
added Elasticsearch credentials to config/pipeline/main.conf. The appliance
already HAD a main.conf, so delivery skipped it, Logstash kept the
credential-less version, and it 401'd into a 24-restart crash loop against an
Elasticsearch that reported healthy throughout. The fix existed upstream and had
no route to the box.

It refuses to touch DIRECTORIES that already exist. A mounted directory mixes
shipped defaults with operator state — timesketch mounts its whole ./config,
which the backend writes LLM settings into — and cannot be reasoned about from
here. It also refuses to delete a non-empty directory standing where a file
belongs: that is data, and no upgrade gets to remove it to make a mount fit.
"""

import filecmp
import os
import posixpath
import shutil
from typing import Callable, Dict, List, NamedTuple

from .base import WORKDIR


class BindRef(NamedTuple):
    """One host path a compose file depends on."""
    service: str          # compose service that declares it
    source: str           # as written, relative to the module directory
    target: str           # container path ('' for env_file)
    repo_path: str        # normalised, relative to the Intact.AI root
    executed: bool        # the service's entrypoint/command runs this target


# Bind sources that are NOT in the release source tree because something on the
# appliance creates them. Keys are Intact.AI-root-relative. A missing entry here
# for an untracked mount is a CI failure, not a runtime surprise — the point of
# the list is that adding a mount forces you to say who creates it.
INSTALL_GENERATED: Dict[str, str] = {
    'modules/nginx/ssl/nginx-cert.crt':
        'self-signed cert generated by install.sh (lib/nginx.sh)',
    'modules/nginx/ssl/nginx-cert.key':
        'self-signed key generated by install.sh (lib/nginx.sh)',
    'modules/nginx/html/downloads':
        'Velociraptor binaries staged at install/upgrade (lib/docker.sh)',
    'modules/portainer/secrets/admin_password':
        'generated on first Portainer install (upgrade/portainer.py)',
    'modules/portainer/secrets/agent.env':
        'generated on first Portainer install (upgrade/portainer.py)',
    'modules/timesketch/secrets/postgres.env':
        'generated by ensure_postgres_password (upgrade/timesketch.py)',
    'modules/velociraptor/config':
        'server/client configs generated at install (lib/velociraptor.sh)',
    'client_installers':
        'MSI/DEB installers generated on demand by the backend',
    'data':
        'SQLite database and runtime state, created at install',
    '.':
        'the Intact.AI root itself, mounted for upgrade operations',
}

# Compose progress chatter, so a caller reporting a failure can strip it and
# show the actual error. Docker writes these to STDERR interleaved with real
# diagnostics, and they are what buried the ELK "exit 126" line.
_PROGRESS_VERBS = (
    'Creating', 'Created', 'Starting', 'Started', 'Stopping', 'Stopped',
    'Removing', 'Removed', 'Recreate', 'Recreated', 'Running', 'Waiting',
    'Healthy', 'Pulling', 'Pulled', 'Built', 'Building', 'Skipped',
)


def _module_dir_repo_path(module_name: str) -> str:
    return posixpath.join('modules', module_name)


def _normalise(module_name: str, source: str) -> str:
    """Resolve a compose-relative bind source to an Intact.AI-root-relative
    path. './config/x' under elk -> 'modules/elk/config/x';
    '../nginx/ssl/y' -> 'modules/nginx/ssl/y'; '../..' -> '.'."""
    return posixpath.normpath(
        posixpath.join(_module_dir_repo_path(module_name), source))


_INTERPRETERS = {'sh', 'bash', 'ash', 'dash', 'zsh', 'env',
                 'python', 'python3', 'perl', 'ruby'}


def _tokens(val) -> List[str]:
    if isinstance(val, str):
        return val.split()
    if isinstance(val, list):
        return [str(v) for v in val]
    return []


def _executed_targets(service: dict) -> List[str]:
    """The container path the service actually RUNS, if any.

    Only argv[0] counts, and only that. An argument that merely happens to be a
    path is not executed -- Portainer's

        command: -H tcp://portainer-agent:9001 --tlscert /certs/cert.pem ...

    names three mounted paths as option values, and treating those as executed
    would abort every Portainer upgrade over certs that install.sh legitimately
    creates later. Splitting the whole command line on whitespace did exactly
    that on the first run of this code.

    Two shapes have to resolve to the same answer:

        entrypoint: ["/bin/bash", "/usr/local/bin/setup-kibana-user.sh"]   (elk)
        entrypoint: /bin/bash
        command: [/postgres_start_with_secrets.sh]                         (iris)

    so when argv[0] is an interpreter, the program is the first absolute path
    after it -- across the entrypoint/command boundary, since compose
    concatenates them.
    """
    ep, cmd = _tokens(service.get('entrypoint')), _tokens(service.get('command'))
    argv = ep + cmd
    if not argv:
        return []
    if ep:
        if os.path.basename(argv[0]) in _INTERPRETERS:
            for tok in argv[1:]:
                if tok.startswith('-'):
                    continue  # interpreter flag (-c, -u, ...), not the program
                return [tok] if tok.startswith('/') else []
            return []
        return [argv[0]]
    # No entrypoint: the image's own ENTRYPOINT may prepend argv, so command[0]
    # is the program only when it is written as an absolute path.
    return [argv[0]] if argv[0].startswith('/') else []


def iter_bind_sources(compose_path: str, module_name: str) -> List[BindRef]:
    """Every relative host path `compose_path` depends on, from both `volumes:`
    and `env_file:`. Absolute paths (/var/run/docker.sock, /tmp/plaso) belong to
    the host, named volumes belong to Docker, and anything carrying a `${VAR}`
    cannot be resolved without the environment — all three are skipped."""
    import yaml
    with open(compose_path, 'r') as f:
        doc = yaml.safe_load(f) or {}
    refs: List[BindRef] = []
    for svc_name, svc in (doc.get('services') or {}).items():
        if not isinstance(svc, dict):
            continue
        executed = _executed_targets(svc)

        def _add(source: str, target: str):
            if not source or '$' in source:
                return
            if not (source.startswith('./') or source.startswith('../')
                    or source in ('.', '..')):
                return  # absolute host path, or a named volume
            refs.append(BindRef(
                service=svc_name, source=source, target=target,
                repo_path=_normalise(module_name, source),
                executed=bool(target) and target in executed))

        for vol in (svc.get('volumes') or []):
            if isinstance(vol, str):
                # short syntax: SOURCE:TARGET[:MODE]
                parts = vol.split(':')
                if len(parts) >= 2:
                    _add(parts[0], parts[1])
            elif isinstance(vol, dict) and vol.get('type') == 'bind':
                _add(str(vol.get('source') or ''), str(vol.get('target') or ''))

        env_file = svc.get('env_file')
        if isinstance(env_file, str):
            _add(env_file, '')
        elif isinstance(env_file, list):
            for e in env_file:
                if isinstance(e, str):
                    _add(e, '')
                elif isinstance(e, dict):
                    _add(str(e.get('path') or ''), '')
    return refs


def deliver_referenced_assets(module_name: str, intact_root: str,
                              logger: Callable = None) -> int:
    """Copy every file the module's NEW compose file bind-mounts that the
    release source tree has and the appliance does not.

    Fill-the-gap only — an existing path is never overwritten, because mounted
    directories hold operator state alongside shipped defaults. Modes are
    preserved via copy2/copystat: the mounted files are frequently scripts, and
    a delivered-but-not-executable script fails exactly as loudly as a missing
    one (`chmod +x` under a restrictive umask has bitten this codebase before).

    Returns the number of paths delivered. Never raises — a delivery failure
    downgrades to the verify step, which reports it against the real appliance
    state rather than guessing here.
    """
    log = logger or (lambda msg, level="info": print(f"[{level}] {msg}"))
    compose = os.path.join(WORKDIR, 'modules', module_name, 'docker-compose.yaml')
    if not os.path.isfile(compose):
        return 0
    try:
        refs = iter_bind_sources(compose, module_name)
    except Exception as e:
        log(f"  Could not read {module_name} compose mounts "
            f"({type(e).__name__}: {e}) — skipping asset delivery", "warning")
        return 0

    delivered = 0
    for ref in refs:
        dst = os.path.join(WORKDIR, ref.repo_path)
        src = os.path.join(intact_root, ref.repo_path)
        if os.path.exists(dst):
            # A box that ALREADY hit this bug has Docker's empty directory
            # sitting exactly where the file belongs. A plain exists() check
            # calls that "delivered" and leaves the box broken through every
            # future upgrade — the repair has to be able to undo the damage,
            # not just avoid causing it. Only ever an EMPTY directory standing
            # in for a file: anything with contents is real data, and no
            # upgrade gets to delete that.
            if not (os.path.isdir(dst) and os.path.isfile(src)):
                continue
            try:
                if os.listdir(dst):
                    log(f"  {ref.repo_path} is a non-empty directory where "
                        f"{ref.service} expects a file — leaving it alone; "
                        f"this needs a human", "warning")
                    continue
                os.rmdir(dst)
                log(f"  Removed the empty directory Docker created at "
                    f"{ref.repo_path} (a previous run mounted a file that was "
                    f"never delivered)", "warning")
            except Exception as e:
                log(f"  Could not clear {ref.repo_path} "
                    f"({type(e).__name__}: {e})", "warning")
                continue
        if not os.path.exists(src):
            continue  # install-generated; verify_referenced_assets reports it
        if os.path.isfile(dst) and os.path.isfile(src):
            # REFRESH a shipped config file whose content changed.
            #
            # Fill-the-gap alone is not enough, and the proof arrived the same
            # day: the ELK release that enabled xpack.security also added
            # Elasticsearch credentials to config/pipeline/main.conf. The
            # appliance already HAD a main.conf, so delivery skipped it,
            # Logstash kept the credential-less version, and it 401'd into a
            # 24-restart crash loop against an Elasticsearch that reported
            # healthy the whole time. The fix existed upstream and could not
            # reach the box.
            #
            # Only single mounted FILES, never directories: a mounted directory
            # (timesketch's ./config) mixes shipped defaults with operator state
            # and cannot be reasoned about file by file from here. And the
            # previous content is kept beside it, so a local edit is recoverable
            # rather than destroyed.
            try:
                if filecmp.cmp(src, dst, shallow=False):
                    continue
                backup = dst + '.pre-upgrade'
                shutil.copy2(dst, backup)
                shutil.copy2(src, dst)
                shutil.copystat(src, dst)
                log(f"  Refreshed {ref.repo_path} from the new release "
                    f"({ref.service} mounts it); previous content kept at "
                    f"{os.path.basename(backup)}", "success")
                delivered += 1
            except Exception as e:
                log(f"  Could not refresh {ref.repo_path} "
                    f"({type(e).__name__}: {e})", "warning")
            continue
        try:
            os.makedirs(os.path.dirname(dst.rstrip('/')) or '/', exist_ok=True)
            if os.path.isdir(src):
                shutil.copytree(src, dst)
            else:
                shutil.copy2(src, dst)
                shutil.copystat(src, dst)
            mode = oct(os.stat(dst).st_mode & 0o777)[2:]
            log(f"  Delivered {ref.repo_path} (mode {mode}) — required by the "
                f"new {module_name} compose file, service '{ref.service}'",
                "success")
            delivered += 1
        except Exception as e:
            log(f"  Could not deliver {ref.repo_path} "
                f"({type(e).__name__}: {e})", "warning")
    return delivered


def verify_referenced_assets(module_name: str,
                             logger: Callable = None) -> List[str]:
    """Check the appliance immediately before `docker compose up`.

    Returns a list of FATAL findings — bind sources that are missing and whose
    target the service executes. Docker would create a directory at each and the
    container would exit 126; failing here instead names the file. Missing paths
    that are merely mounted (not executed) are logged as warnings rather than
    aborting: some are legitimately created by a later step of the same run.
    """
    log = logger or (lambda msg, level="info": print(f"[{level}] {msg}"))
    compose = os.path.join(WORKDIR, 'modules', module_name, 'docker-compose.yaml')
    if not os.path.isfile(compose):
        return []
    try:
        refs = iter_bind_sources(compose, module_name)
    except Exception as e:
        log(f"  Could not read {module_name} compose mounts "
            f"({type(e).__name__}: {e}) — skipping mount preflight", "warning")
        return []

    fatal: List[str] = []
    for ref in refs:
        path = os.path.join(WORKDIR, ref.repo_path)
        if os.path.exists(path):
            # Present, but is it RUNNABLE? A delivered-but-not-executable
            # script fails exactly as loudly as a missing one, and this repo has
            # shipped one before: `chmod +x` (symbolic, no "who") is filtered by
            # the process umask, `chmod 755` is not. Repair rather than refuse —
            # the correct mode is not a judgement call, and an operator staring
            # at exit 126 at 2am should not have to make it.
            if ref.executed and os.path.isfile(path):
                mode = os.stat(path).st_mode & 0o777
                if not mode & 0o111:
                    try:
                        os.chmod(path, mode | 0o755)
                        log(f"  Repaired {ref.repo_path}: mode {oct(mode)[2:]} "
                            f"-> 755 ({ref.service} execs it; it would have "
                            f"exited 126)", "warning")
                    except Exception as e:
                        fatal.append(
                            f"{module_name}: {ref.repo_path} is not executable "
                            f"(mode {oct(mode)[2:]}) and could not be repaired "
                            f"({type(e).__name__}: {e}); service "
                            f"'{ref.service}' runs it and would exit 126.")
            elif ref.executed and os.path.isdir(path):
                fatal.append(
                    f"{module_name}: {ref.repo_path} is a DIRECTORY where "
                    f"service '{ref.service}' expects the program {ref.target}. "
                    f"Docker creates one automatically when a bind-mounted file "
                    f"is missing, so this box ran an upgrade that did not "
                    f"deliver it; the container would exit 126.")
            continue
        if ref.executed:
            fatal.append(
                f"{module_name}: compose service '{ref.service}' runs "
                f"{ref.target}, mounted from {ref.repo_path}, which does not "
                f"exist. Docker would create an empty DIRECTORY there and the "
                f"container would exit 126. The upgrade package is missing "
                f"this file.")
            continue
        why = INSTALL_GENERATED.get(ref.repo_path)
        log(f"  {module_name}: {ref.repo_path} is missing"
            + (f" ({why}) — it will be created as an empty directory if "
               f"nothing provisions it first" if why else
               " and is not a known install-generated path; Docker will "
               "create an empty directory there"),
            "info" if why else "warning")
    for f in fatal:
        log(f"  {f}", "error")
    return fatal


def strip_compose_progress(stderr: str, limit: int = 600) -> str:
    """Compose writes 'Container X Creating/Started/...' progress to STDERR
    interleaved with real errors. Reporting the HEAD of that stream shows only
    chatter — the ELK failure's decisive line ('service "setup" didn't complete
    successfully: exit 126') was the LAST one, and a 200-character head cut it.

    Drops the progress lines and returns what remains; if it was progress all
    the way down, returns the TAIL instead, which is where compose puts its
    summary.
    """
    lines = [ln.rstrip() for ln in (stderr or '').splitlines() if ln.strip()]
    kept = []
    for ln in lines:
        words = ln.split()
        # ' Container intact_elk_setup  Started ' -> noun, name, verb
        if len(words) >= 2 and words[-1] in _PROGRESS_VERBS and \
                words[0] in ('Container', 'Network', 'Volume', 'Image', 'Service'):
            continue
        kept.append(ln)
    out = '\n'.join(kept) if kept else '\n'.join(lines[-4:])
    return out[-limit:] if len(out) > limit else out
