"""The support bundle — collected by this suite for a year, never once asserted.

WHY THIS MATTERS MORE THAN ITS SIZE SUGGESTS. `wrapup.py` already calls
`/api/support-bundle/prepare` and downloads the result, but it does so inside a
bare `try/except` **with no `ctx.check` at all**: the run passes whether the
endpoint returns a bundle, a 500, or nothing. And the comment sitting above that
call reads "It has already been shown to carry secrets."

So the product's own "send this to support" artifact — the file an operator
emails to a vendor, attaches to a ticket, or drops in a shared drive — is
generated by code with no test, is known to have leaked before, and the one
place that touches it asserts nothing.

WHAT IS ASSERTED. That the bundle is real (a ZIP, not an error page), that it
contains the sections an engineer would need, that its manifest describes what
was collected, and — the reason this phase exists — that **no configured
credential appears anywhere inside it**. That last check reuses the same secret
list and scanner the `report` phase already runs over the run directory, because
a bundle is exactly as public as an uploaded artifact and this repo is public.

WHAT IS RECORDED RATHER THAN ASSERTED (per the standing policy — measured on a
live appliance, both are product behaviour, not test failures):

  * the manifest's own `redacted` counter reported {"files": 0, "lines": 0} on a
    bundle that demonstrably contained 8 [REDACTED] markers. The counter is only
    accumulated on the container-log path, so anything redacted elsewhere is
    invisible in the manifest. A reviewer reading it would conclude nothing was
    scrubbed.
  * BUNDLE_OUTPUT_DIR is /data/support_bundles, which is in no compose volume,
    so a bundle prepared and not downloaded before a recreate is gone. The
    download route says so in its own comment.

COST: measured at 30 seconds and 3.4 MB on a live box, so it earns its own phase
rather than being folded into an existing one.
"""

import io
import json
import re
import zipfile

# Sections an engineer opening the bundle needs. Not the full list — these are
# the ones whose absence makes the bundle useless for a support case.
WANT_SECTIONS = ("manifest.json", "containers", "compose", "versions.txt")

BUNDLE_TIMEOUT_MIN = 15


def register(runner, cfg):
    tl = runner.ctx.tl

    @runner.phase("support_bundle",
                  "Generate the support bundle and prove it is safe to send",
                  needs=("features",))
    def support_bundle(ctx):
        c = ctx.get("client")
        detail = {}

        body = c.post("/api/support-bundle/prepare", {}, expect=(200, 201, 202))
        run_id = (body or {}).get("run_id")
        detail["run_id"] = run_id
        ctx.check("the support bundle started", bool(run_id), actual=body)
        if not run_id:
            return detail
        tl.ids(support_bundle_run_id=run_id)

        run = c.wait_for_run(run_id, BUNDLE_TIMEOUT_MIN * 60, tl,
                             what="the support bundle")
        status = (run or {}).get("status")
        detail["status"] = status
        ctx.check("the support bundle finished",
                  status in ("completed", "complete"),
                  expected="completed", actual=status)

        blob = c.raw(f"/api/support-bundle/{run_id}/download", expect=(200,))
        detail["bytes"] = len(blob or b"")
        ctx.check("the download is a ZIP, not an error page",
                  (blob or b"")[:2] == b"PK",
                  expected="PK magic", actual=repr((blob or b"")[:16]),
                  note="a JSON error body downloads perfectly happily and is "
                       "indistinguishable from success at the status-code level")
        if (blob or b"")[:2] != b"PK":
            return detail
        ctx.check("the bundle has real content", len(blob) > 100_000,
                  expected=">100 KB", actual=len(blob),
                  note="an empty archive opens fine and helps nobody")

        try:
            zf = zipfile.ZipFile(io.BytesIO(blob))
            names = zf.namelist()
        except zipfile.BadZipFile as exc:
            ctx.check("the bundle opens as a ZIP", False, actual=str(exc)[:120])
            return detail
        detail["members"] = len(names)
        ctx.check("the bundle opens and holds many files", len(names) > 10,
                  expected=">10 members", actual=len(names))

        root = names[0].split("/")[0] if names else ""
        sections = sorted({n[len(root) + 1:].split("/")[0]
                           for n in names if n[len(root) + 1:]})
        detail["sections"] = sections
        absent = [s for s in WANT_SECTIONS if s not in sections]
        ctx.check("the bundle carries the sections a support case needs",
                  not absent, expected=", ".join(WANT_SECTIONS),
                  actual=", ".join(absent) + " absent" if absent else "all present")

        man = {}
        if f"{root}/manifest.json" in names:
            try:
                man = json.loads(zf.read(f"{root}/manifest.json"))
            except Exception as exc:                          # noqa: BLE001
                detail["manifest_error"] = str(exc)[:120]
        ctx.check("the manifest describes what was collected",
                  bool(man.get("containers")),
                  expected="a container map",
                  actual=len(man.get("containers") or {}),
                  note="the manifest is how an engineer knows what they are "
                       "looking at and what is missing")

        # ------------------------------------------------------------------
        # THE ASSERTION THIS PHASE EXISTS FOR.
        #
        # The same secret list the report phase sweeps the run directory with —
        # and this is the hole that sweep leaves: _scan_for_secrets() skips
        # `.zip` files (reasonably: a memory image legitimately contains
        # whatever was in RAM). The support bundle IS a zip, so nothing has ever
        # looked inside the one artifact most likely to be sent off the box.
        #
        # ALL-DIGIT SECRETS NEED A BOUNDARY, not a substring test. Measured: the
        # default QA dashboard password is six digits, and it matched inside a
        # microsecond timestamp (...T08:24:51.123123004Z) in a container log —
        # a false leak report on a bundle that was in fact clean. Requiring the
        # match not to sit inside a longer run of digits keeps the detection and
        # drops the collision.
        # PASSWORDS ONLY, and this is the fix for a false positive that failed
        # the first real CI run in five separate files. cfg.secrets() is built
        # for REDACTION, so it deliberately includes identity fields as well as
        # credentials: platform.host, platform.sudo_user, windows.host,
        # windows.username. Scrubbing those from a log is harmless; asserting
        # they never appear in a product artifact is not, because CI sets
        # QA_SUDO_USER=runner and every path in every workflow row reads
        # /home/runner/... . Five "leaks", none of them a credential.
        #
        # A leak assertion needs the things that would actually be a
        # disclosure, so this filters SECRET_FIELDS down to the password ones.
        creds = []
        try:
            from lib import config as _qa_config
            for section, key in getattr(_qa_config, "SECRET_FIELDS", ()):
                if "pass" not in key.lower():
                    continue
                v = cfg.get(section, key)
                if isinstance(v, str) and len(v.strip()) >= 6:
                    creds.append(v.strip())
        except Exception:                                     # noqa: BLE001
            creds = []
        secrets = creds or [s for s in (cfg.secrets() or []) if len(s) >= 8]
        matchers = []
        for sec in secrets:
            if sec.isdigit():
                matchers.append((sec, re.compile(r"(?<!\d)" + re.escape(sec) + r"(?!\d)")))
            else:
                matchers.append((sec, None))
        scanned, offenders, redaction_markers = 0, [], 0
        for n in names:
            if n.endswith("/"):
                continue
            try:
                text = zf.read(n).decode("utf-8", "replace")
            except Exception:                                 # noqa: BLE001
                continue
            scanned += 1
            redaction_markers += text.count("[REDACTED]")
            for sec, rx in matchers:
                if (rx.search(text) if rx else (sec in text)):
                    # NAMED, never printed: the member is what an operator needs
                    # to act on, and echoing the value would put it in the run
                    # report this check exists to keep clean.
                    offenders.append(f"{n} (a configured credential)")
                    break
        detail["scanned_members"] = scanned
        detail["secret_values_scanned"] = len(secrets)
        detail["redaction_markers"] = redaction_markers
        detail["offenders"] = offenders
        ctx.check("no configured credential appears in the support bundle",
                  not offenders,
                  expected="none of the configured secrets present",
                  actual=", ".join(offenders[:5]) or f"clean across {scanned} files",
                  note="THE POINT OF THIS PHASE. The bundle is emailed to "
                       "vendors and attached to tickets; a credential inside it "
                       "is a credential disclosed, and the code that builds it "
                       "had no test of any kind")

        # ------------------------------------------------------------------
        # Recorded, not asserted.
        detail["recorded"] = {
            "manifest_redacted_counter": man.get("redacted"),
            "note_counter": (
                "Measured on a live box: the manifest reported "
                "{'files': 0, 'lines': 0} while the archive contained 8 "
                "[REDACTED] markers — the counter is accumulated only on the "
                "container-log path, so redaction done elsewhere is invisible "
                "to anyone reading the manifest."),
            "note_zip_gap": (
                "wrapup's _scan_for_secrets() skips .zip files, so the support "
                "bundle is invisible to the run-directory sweep. This phase is "
                "the only thing that looks inside it."),
            "note_ephemeral": (
                "BUNDLE_OUTPUT_DIR=/data/support_bundles is in no compose "
                "volume, so a bundle prepared and not downloaded before a "
                "recreate is lost; the download route documents this itself."),
        }
        return detail
